### ISSUE TITLE
Login / Quit API

### ISSUE THREAD

**Issue by valderosch** [valderosch/agency-team-project#19]
### Develop an API for Login and Logout

**Task**
Develop an API whick work with sessions and return actual account status (Authorised / Unauthorised)

**To - Do:**

- [x] API returns responce
- [x] API returns current status
- [x] Api return Exception

**Comment by valderosch** [comment]
**Done.**



![Image](https://github.com/valderosch/agency-team-project/assets/82396763/8c5be54c-b1c2-4dac-83ac-74b0ef0ba454)
